name: Percy Visual Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  visual-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Install Percy and test tools
        run: npm install --save-dev @percy/cli @percy/cypress start-server-and-test

      - name: Start server and run visual tests
        run: npx percy exec -- start-server-and-test start http://localhost:3000 'npx cypress run'
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
